language: ruby
cache: bundler
rvm:
  - 2.3
matrix:
  include:
    - # GitHub Pages
      rvm: 2.3.1
      env: JEKYLL_VERSION=3.3.0
env:
  matrix:
    - JEKYLL_VERSION=3.3
branches:
  only:
    - master
